In [1]:
# set dependencies
import pandas as pd
import numpy as np
import matplotlib as plt
import requests
import re as re

In [2]:
# pull FOREX data from fixer site
api_key = "27279b812fe4f25f2c43584f1be9bdb9"

base = {"Date": ["NA"], "Rate": ["NA"]}
df = pd.DataFrame(base)

months = ["01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12"]
countries = ["USD", "GBP", "JPY", "CNY"]
# countries = ["XAU"]

for i in months:
    for j in range(2005, 2015):
        for c in countries:
            url = f"http://data.fixer.io/api/{j}-{i}-01?access_key={api_key}&base=EUR&symbols={c}"

            curr = requests.get(url)
            curr_js = curr.json()

            date = curr_js["date"]
        
            rate = curr_js["rates"]

            d = {"Date": [date], "Rate": [rate]}
            df2 = pd.DataFrame(d)
        
            df = df.append(df2)

In [3]:
# cleaner code...
df.reset_index(inplace = True, drop = True)
df = df.drop([0])

In [2]:
# df.to_excel("D:/Git/MChinchilla_GW_HW/07_Project_01/forex_dta.xlsx")
df = pd.read_excel("D:/Git/MChinchilla_GW_HW/07_Project_01/forex_dta.xlsx")

In [3]:
df['Currency'] = df['Rate'].str.extract('([A-Z][A-Z][A-Z])', expand=True)
df['Rate_c'] = df['Rate'].str.extract('([0-9]+[.][0-9]+)', expand=True)

In [4]:
df = df.loc[:, ["Date", "Currency", "Rate_c"]]
df.columns = ["Date", "Currency", "Rate"]
df

           Date Currency        Rate
0    2005-01-01      USD    1.358363
1    2005-01-01      GBP    0.705819
2    2005-01-01      JPY  139.436301
3    2005-01-01      CNY    11.23808
4    2006-01-01      USD    1.181562
5    2006-01-01      GBP    0.686612
6    2006-01-01      JPY   139.22724
7    2006-01-01      CNY    9.537388
8    2007-01-01      USD    1.315192
9    2007-01-01      GBP    0.670411
10   2007-01-01      JPY  156.436232
11   2007-01-01      CNY   10.266779
12   2008-01-01      USD    1.462424
13   2008-01-01      GBP    0.735121
14   2008-01-01      JPY  163.416069
15   2008-01-01      CNY   10.685003
16   2009-01-01      USD    1.394492
17   2009-01-01      GBP    0.956164
18   2009-01-01      JPY  126.598325
19   2009-01-01      CNY    9.517772
20   2010-01-01      USD      1.4342
21   2010-01-01      GBP    0.886657
22   2010-01-01      JPY  133.252538
23   2010-01-01      CNY    9.793804
24   2011-01-01      USD     1.33737
25   2011-01-01      GBP    0.859052
26   2011-01-01      JPY   108.47771
27   2011-01-01      CNY    8.824843
28   2012-01-01      USD    1.294525
29   2012-01-01      GBP    0.834192
..          ...      ...         ...
450  2007-12-01      JPY  163.057094
451  2007-12-01      CNY   10.878142
452  2008-12-01      USD     1.26484
453  2008-12-01      GBP    0.847792
454  2008-12-01      JPY  118.466521
455  2008-12-01      CNY    8.708866
456  2009-12-01      USD     1.50901
457  2009-12-01      GBP    0.908811
458  2009-12-01      JPY  130.906873
459  2009-12-01      CNY    10.30251
460  2010-12-01      USD     1.31355
461  2010-12-01      GBP    0.840966
462  2010-12-01      JPY   110.49819
463  2010-12-01      CNY    8.752748
464  2011-12-01      USD    1.347397
465  2011-12-01      GBP    0.858447
466  2011-12-01      JPY  104.659436
467  2011-12-01      CNY    8.577905
468  2012-12-01      USD    1.298858
469  2012-12-01      GBP    0.810988
470  2012-12-01      JPY  107.017645
471  2012-12-01      CNY    8.101238
472  2013-12-01      USD    1.359019
473  2013-12-01      GBP    0.829977
474  2013-12-01      JPY  139.254578
475  2013-12-01      CNY    8.290846
476  2014-12-01      USD    1.247301
477  2014-12-01      GBP    0.792686
478  2014-12-01      JPY  147.651021
479  2014-12-01      CNY    7.668639

[480 rows x 3 columns]

In [ ]:
# export file as xlsx to share with team
df.to_excel("D:/Git/MChinchilla_GW_HW/07_Project_01/forex_dta.xlsx")